-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2025-08-30 01:54:00 MYT
--   site:      Oracle Database 12c
--   type:      Converted to PostgreSQL

-- Drop tables if they exist
DROP TABLE IF EXISTS clause CASCADE;
DROP TABLE IF EXISTS contract CASCADE;
DROP TABLE IF EXISTS contract_clause_match CASCADE;
DROP TABLE IF EXISTS contract_issue CASCADE;
DROP TABLE IF EXISTS contract_summary CASCADE;
DROP TABLE IF EXISTS contract_text CASCADE;
DROP TABLE IF EXISTS contract_translation CASCADE;
DROP TABLE IF EXISTS derived_wage_rate CASCADE;
DROP TABLE IF EXISTS dim_nationality CASCADE;
DROP TABLE IF EXISTS dim_sector CASCADE;
DROP TABLE IF EXISTS dim_state CASCADE;
DROP TABLE IF EXISTS dim_year CASCADE;
DROP TABLE IF EXISTS employment_detail CASCADE;
DROP TABLE IF EXISTS legal_topic_mapping CASCADE;
DROP TABLE IF EXISTS media_asset CASCADE;
DROP TABLE IF EXISTS migrant_by_nationality CASCADE;
DROP TABLE IF EXISTS migrant_by_state CASCADE;
DROP TABLE IF EXISTS migrant_sector_visual CASCADE;
DROP TABLE IF EXISTS migrant_summary CASCADE;
DROP TABLE IF EXISTS nationality_sector CASCADE;
DROP TABLE IF EXISTS organization CASCADE;
DROP TABLE IF EXISTS organization_language CASCADE;
DROP TABLE IF EXISTS payslip CASCADE;
DROP TABLE IF EXISTS payslip_item CASCADE;
DROP TABLE IF EXISTS preferred_language CASCADE;
DROP TABLE IF EXISTS quiz_answer CASCADE;
DROP TABLE IF EXISTS quiz_option CASCADE;
DROP TABLE IF EXISTS quiz_question CASCADE;
DROP TABLE IF EXISTS quiz_result CASCADE;
DROP TABLE IF EXISTS ref_legal_section CASCADE;
DROP TABLE IF EXISTS rights_topic CASCADE;
DROP TABLE IF EXISTS source_register CASCADE;
DROP TABLE IF EXISTS story_media CASCADE;
DROP TABLE IF EXISTS survivor_story CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS work_log CASCADE;

CREATE TABLE clause (
    clause_id                BIGINT NOT NULL,
    clause_category          CHAR(30),
    clause_title_en          VARCHAR(250),
    clause_expe_reqt_text_en VARCHAR(250),
    violation_message_en     TEXT,
    language_code            CHAR(2) NOT NULL,
    source_id                INTEGER NOT NULL,
    legal_id                 INTEGER NOT NULL
);

COMMENT ON COLUMN clause.clause_id IS 'clause_id';
COMMENT ON COLUMN clause.clause_category IS 'clause_category';
COMMENT ON COLUMN clause.clause_title_en IS 'minimum wage, maximum working hour, passport retention';
COMMENT ON COLUMN clause.clause_expe_reqt_text_en IS 'clause_expected_requirement_text_en';
COMMENT ON COLUMN clause.violation_message_en IS 'violation_message_en';
COMMENT ON COLUMN clause.language_code IS 'language_code
Malay: MS
English: EN
Nepali: NE
Hindi: HI
Bengali: BN';
COMMENT ON COLUMN clause.source_id IS 'source_id';
COMMENT ON COLUMN clause.legal_id IS 'legal_id ';

CREATE UNIQUE INDEX clause__idx ON clause (language_code ASC, source_id ASC, legal_id ASC);
ALTER TABLE clause ADD CONSTRAINT clause_pk PRIMARY KEY (clause_id);

CREATE TABLE contract (
    contract_id             INTEGER NOT NULL,
    contract_language       CHAR(25),
    contract_whether_masked CHAR(20),
    user_id                 INTEGER NOT NULL,
    media_id                BIGINT NOT NULL
);

COMMENT ON COLUMN contract.contract_id IS 'contract_id';
COMMENT ON COLUMN contract.contract_language IS 'contract_language';
COMMENT ON COLUMN contract.contract_whether_masked IS 'whether sensitive personal info from uploaded contract has been masked
''None'' no masking
''Auto'' automatic masking using regex or ML
''Manual'' human reviewed/correct masking';
COMMENT ON COLUMN contract.user_id IS 'user_id';
COMMENT ON COLUMN contract.media_id IS 'media_id';

CREATE UNIQUE INDEX contract__idx ON contract (user_id ASC);
ALTER TABLE contract ADD CONSTRAINT contract_pk PRIMARY KEY (contract_id, user_id);

CREATE TABLE contract_clause_match (
    match_id         BIGINT NOT NULL,
    match_span_start INTEGER,
    match_span_end   INTEGER,
    match_excerpt    VARCHAR(300),
    contract_text_id BIGINT NOT NULL,
    clause_id        BIGINT NOT NULL,
    contract_id      INTEGER NOT NULL,
    user_id          INTEGER NOT NULL
);

COMMENT ON COLUMN contract_clause_match.match_id IS 'match_id';
COMMENT ON COLUMN contract_clause_match.match_span_start IS 'highlight/underline start of exact part of contract clause';
COMMENT ON COLUMN contract_clause_match.match_span_end IS 'highlight/underline end of exact part of contract clause';
COMMENT ON COLUMN contract_clause_match.match_excerpt IS 'store the suspicious clause separately to avoid reloading the entire contract ';
COMMENT ON COLUMN contract_clause_match.contract_text_id IS 'contract_text_id';
COMMENT ON COLUMN contract_clause_match.clause_id IS 'clause_id';
COMMENT ON COLUMN contract_clause_match.contract_id IS 'contract_id';
COMMENT ON COLUMN contract_clause_match.user_id IS 'user_id';

CREATE UNIQUE INDEX contract_clause_match__idx ON contract_clause_match (clause_id ASC);
CREATE UNIQUE INDEX contract_clause_match__idxv1 ON contract_clause_match (contract_text_id ASC, contract_id ASC, user_id ASC);
ALTER TABLE contract_clause_match ADD CONSTRAINT contract_clause_match_pk PRIMARY KEY (match_id, contract_text_id, contract_id, user_id);

CREATE TABLE contract_issue (
    issue_id                BIGINT NOT NULL,
    issue_status            VARCHAR(25),
    issue_explanation_en    TEXT,
    issue_recommendation_en TEXT,
    contract_id             INTEGER NOT NULL,
    user_id                 INTEGER NOT NULL,
    clause_id               BIGINT NOT NULL
);

COMMENT ON COLUMN contract_issue.issue_id IS 'issue_id';
COMMENT ON COLUMN contract_issue.issue_status IS '''potential'', ''confirmed'', ''not-applicable''
DEFAULT ''potential''';
COMMENT ON COLUMN contract_issue.issue_explanation_en IS 'plain language';
COMMENT ON COLUMN contract_issue.issue_recommendation_en IS 'what to fix ';
COMMENT ON COLUMN contract_issue.contract_id IS 'contract_id';
COMMENT ON COLUMN contract_issue.user_id IS 'user_id';
COMMENT ON COLUMN contract_issue.clause_id IS 'clause_id';

CREATE UNIQUE INDEX contract_issue__idx ON contract_issue (contract_id ASC, user_id ASC);
CREATE UNIQUE INDEX contract_issue__idxv1 ON contract_issue (clause_id ASC);
ALTER TABLE contract_issue ADD CONSTRAINT contract_issue_pk PRIMARY KEY (issue_id, contract_id, user_id);

CREATE TABLE contract_summary (
    contract_summary_id     INTEGER NOT NULL,
    contract_summary_status CHAR(25),
    summary_plain_language  TEXT,
    contract_id             INTEGER NOT NULL,
    user_id                 INTEGER NOT NULL
);

COMMENT ON COLUMN contract_summary.contract_summary_id IS 'contract_summary_id';
COMMENT ON COLUMN contract_summary.contract_summary_status IS '''no issues'', ''potential issues''';
COMMENT ON COLUMN contract_summary.summary_plain_language IS 'summary_plain_language';
COMMENT ON COLUMN contract_summary.contract_id IS 'contract_id';
COMMENT ON COLUMN contract_summary.user_id IS 'user_id';

CREATE UNIQUE INDEX contract_summary__idx ON contract_summary (contract_id ASC, user_id ASC);
ALTER TABLE contract_summary ADD CONSTRAINT contract_summary_pk PRIMARY KEY (contract_summary_id, contract_id, user_id);

CREATE TABLE contract_text (
    contract_text_id           BIGINT NOT NULL,
    contract_extraction_method CHAR(25),
    contract_text_content_en   TEXT,
    contract_id                INTEGER NOT NULL,
    user_id                    INTEGER NOT NULL
);

COMMENT ON COLUMN contract_text.contract_text_id IS 'contract_text_id';
COMMENT ON COLUMN contract_text.contract_extraction_method IS 'contract_extraction_method';
COMMENT ON COLUMN contract_text.contract_text_content_en IS 'contract_text_content_en';
COMMENT ON COLUMN contract_text.contract_id IS 'contract_id';
COMMENT ON COLUMN contract_text.user_id IS 'user_id';

ALTER TABLE contract_text ADD CONSTRAINT contract_text_pk PRIMARY KEY (contract_text_id, contract_id, user_id);

CREATE TABLE contract_translation (
    contract_trans_id          BIGINT NOT NULL,
    contract_trans_target_lang CHAR(25),
    contract_trans_status      CHAR(25),
    contract_transl_text       TEXT,
    contract_text_id           BIGINT NOT NULL,
    contract_id                INTEGER NOT NULL,
    user_id                    INTEGER NOT NULL
);

COMMENT ON COLUMN contract_translation.contract_trans_id IS 'contract_trans_id';
COMMENT ON COLUMN contract_translation.contract_trans_target_lang IS 'contract_trans_target_lang';
COMMENT ON COLUMN contract_translation.contract_trans_status IS '''queued'', ''running'', ''done'', ''failed''';
COMMENT ON COLUMN contract_translation.contract_transl_text IS 'contract_transl_text';
COMMENT ON COLUMN contract_translation.contract_text_id IS 'contract_text_id';
COMMENT ON COLUMN contract_translation.contract_id IS 'contract_id';
COMMENT ON COLUMN contract_translation.user_id IS 'user_id';

CREATE UNIQUE INDEX contract_translation__idx ON contract_translation (contract_text_id ASC, contract_id ASC, user_id ASC);
ALTER TABLE contract_translation ADD CONSTRAINT contract_translation_pk PRIMARY KEY (contract_trans_id, contract_text_id, contract_id, user_id);

CREATE TABLE derived_wage_rate (
    wage_rate_id                 INTEGER NOT NULL,
    law_based_min_monthly        NUMERIC(10,2) NOT NULL,
    ot_multiplier_weekday        NUMERIC(4,2) NOT NULL,
    ot_multiplier_restday        NUMERIC(4,2) NOT NULL,
    ot_multiplier_public_holiday NUMERIC(4,2) NOT NULL,
    law_based_max_hr_per_wk      NUMERIC(4,1),
    law_based_start_date         DATE,
    law_based_end_date           DATE,
    periodicity                  CHAR(10),
    rate_amount                  NUMERIC(10,2),
    currency_code                VARCHAR(3),
    effective_from               DATE,
    state_region                 CHAR(25),
    language_code                CHAR(2) NOT NULL,
    source_id                    INTEGER NOT NULL,
    legal_id                     INTEGER NOT NULL
);

COMMENT ON COLUMN derived_wage_rate.wage_rate_id IS 'wage_rate_id';
COMMENT ON COLUMN derived_wage_rate.law_based_min_monthly IS 'law_based_min_monthly';
COMMENT ON COLUMN derived_wage_rate.ot_multiplier_weekday IS 'law_based_ot_multiplier_weekday';
COMMENT ON COLUMN derived_wage_rate.ot_multiplier_restday IS 'law_based_ot_multiplier_restday';
COMMENT ON COLUMN derived_wage_rate.ot_multiplier_public_holiday IS 'law_based_ot_multiplier_public_holiday';
COMMENT ON COLUMN derived_wage_rate.law_based_max_hr_per_wk IS 'law_based_max_hr_per_wk';
COMMENT ON COLUMN derived_wage_rate.law_based_start_date IS 'law_based_start_date';
COMMENT ON COLUMN derived_wage_rate.law_based_end_date IS 'law_based_end_date';
COMMENT ON COLUMN derived_wage_rate.periodicity IS '''hourly'',''monthly''';
COMMENT ON COLUMN derived_wage_rate.rate_amount IS 'rate_rm';
COMMENT ON COLUMN derived_wage_rate.currency_code IS 'DEFAULT ''MYR''
Indonesia ''IDR'', Nepal ''NPR'', Bangladesh "BDT", India "INR"';
COMMENT ON COLUMN derived_wage_rate.effective_from IS 'effective_from';
COMMENT ON COLUMN derived_wage_rate.state_region IS 'region (Peninsular/Sabah/Sarawak/Federal Territory)';
COMMENT ON COLUMN derived_wage_rate.language_code IS 'language_code
Malay: MS
English: EN
Nepali: NE
Hindi: HI
Bengali: BN';
COMMENT ON COLUMN derived_wage_rate.source_id IS 'source_id';
COMMENT ON COLUMN derived_wage_rate.legal_id IS 'legal_id ';

CREATE UNIQUE INDEX derived_wage_rate__idx ON derived_wage_rate (language_code ASC, source_id ASC, legal_id ASC);
ALTER TABLE derived_wage_rate ADD CONSTRAINT law_based_wage_pk PRIMARY KEY (wage_rate_id);

CREATE TABLE dim_nationality (
    nationality_id       SMALLINT NOT NULL,
    nationality_iso_code CHAR(3),
    nationality_name_en  VARCHAR(20)
);

COMMENT ON COLUMN dim_nationality.nationality_id IS 'nationality_id';
COMMENT ON COLUMN dim_nationality.nationality_iso_code IS 'Malaysia (MYS), Indonesia (INA), Nepal (NPL), Bangladesh (BGD), India IND)';
COMMENT ON COLUMN dim_nationality.nationality_name_en IS 'nationality_name_en
Malaysia, Indonesia, Nepal, Bangladesh, India';

ALTER TABLE dim_nationality ADD CONSTRAINT dim_nationality_pk PRIMARY KEY (nationality_id);

CREATE TABLE dim_sector (
    sector_id          SMALLINT NOT NULL,
    sector_name        CHAR(25),
    sector_description VARCHAR(300)
);

COMMENT ON COLUMN dim_sector.sector_id IS 'sector';
COMMENT ON COLUMN dim_sector.sector_name IS 'sector_name';
COMMENT ON COLUMN dim_sector.sector_description IS 'sector_description';

ALTER TABLE dim_sector ADD CONSTRAINT dim_sector_pk PRIMARY KEY (sector_id);

CREATE TABLE dim_state (
    state_code    INTEGER NOT NULL,
    state_name_en CHAR(50)
);

COMMENT ON COLUMN dim_state.state_code IS 'state_code';
COMMENT ON COLUMN dim_state.state_name_en IS 'state_name_en';

ALTER TABLE dim_state ADD CONSTRAINT dim_state_pk PRIMARY KEY (state_code);

CREATE TABLE dim_year (
    year_id   SMALLINT NOT NULL,
    year      DATE,
    is_latest CHAR(3)
);

COMMENT ON COLUMN dim_year.year_id IS 'year_id';
COMMENT ON COLUMN dim_year.year IS 'year';
COMMENT ON COLUMN dim_year.is_latest IS '''Yes'' , ''No''';

ALTER TABLE dim_year ADD CONSTRAINT dim_year_pk PRIMARY KEY (year_id);

CREATE TABLE employment_detail (
    employ_id             BIGINT NOT NULL,
    employ_job_title      VARCHAR(250) NOT NULL,
    employ_start_date     DATE,
    employ_end_date       DATE,
    employ_pay_cycle      VARCHAR(25),
    employ_base_rate      NUMERIC(10,2) NOT NULL,
    employ_base_rate_type CHAR(15) NOT NULL,
    employ_currency       CHAR(3),
    user_id               INTEGER NOT NULL
);

COMMENT ON COLUMN employment_detail.employ_id IS 'employ_id';
COMMENT ON COLUMN employment_detail.employ_job_title IS 'employ_job_title';
COMMENT ON COLUMN employment_detail.employ_start_date IS 'employ_start_date';
COMMENT ON COLUMN employment_detail.employ_end_date IS 'employ_end_date';
COMMENT ON COLUMN employment_detail.employ_pay_cycle IS 'daily, weekly, biweekly, monthly ';
COMMENT ON COLUMN employment_detail.employ_base_rate IS 'employ_base_rate';
COMMENT ON COLUMN employment_detail.employ_base_rate_type IS 'hourly, monthly';
COMMENT ON COLUMN employment_detail.employ_currency IS 'DEFAULT ''MYR''';
COMMENT ON COLUMN employment_detail.user_id IS 'user_id';

CREATE UNIQUE INDEX employment_detail__idx ON employment_detail (user_id ASC);
ALTER TABLE employment_detail ADD CONSTRAINT employment_detail_pk PRIMARY KEY (employ_id, user_id);

CREATE TABLE legal_topic_mapping (
    legal_topic_mapping_id INTEGER NOT NULL,
    language_code          CHAR(2) NOT NULL,
    source_id              INTEGER NOT NULL,
    legal_id               INTEGER NOT NULL,
    topic_id               INTEGER NOT NULL
);

COMMENT ON COLUMN legal_topic_mapping.legal_topic_mapping_id IS 'legal_topic_mapping_id';
COMMENT ON COLUMN legal_topic_mapping.language_code IS 'language_code
Malay: MS
English: EN
Nepali: NE
Hindi: HI
Bengali: BN';
COMMENT ON COLUMN legal_topic_mapping.source_id IS 'source_id';
COMMENT ON COLUMN legal_topic_mapping.legal_id IS 'legal_id ';
COMMENT ON COLUMN legal_topic_mapping.topic_id IS 'topic_id';

ALTER TABLE legal_topic_mapping ADD CONSTRAINT legal_topic_mapping_pkv1 PRIMARY KEY (legal_topic_mapping_id);
ALTER TABLE legal_topic_mapping ADD CONSTRAINT legal_topic_mapping_pk UNIQUE (language_code, source_id, legal_id, topic_id, legal_topic_mapping_id);
ALTER TABLE legal_topic_mapping ADD CONSTRAINT legal_topic_mapping_nk UNIQUE (legal_id, topic_id);

CREATE TABLE media_asset (
    media_id              BIGINT NOT NULL,
    media_type            VARCHAR(25) NOT NULL,
    media_duration_second INTEGER,
    media_width           INTEGER,
    media_height          INTEGER
);

COMMENT ON COLUMN media_asset.media_id IS 'media_id';
COMMENT ON COLUMN media_asset.media_type IS 'text/html, image/jpeg, video/mp4';
COMMENT ON COLUMN media_asset.media_duration_second IS 'media_duration_second';
COMMENT ON COLUMN media_asset.media_width IS 'media_width_height';
COMMENT ON COLUMN media_asset.media_height IS 'media_height';

ALTER TABLE media_asset ADD CONSTRAINT media_asset_pk PRIMARY KEY (media_id);

CREATE TABLE migrant_by_nationality (
    nationality_id     SMALLINT NOT NULL,
    nationality_number INTEGER
);

COMMENT ON COLUMN migrant_by_nationality.nationality_id IS 'nationality_id';
COMMENT ON COLUMN migrant_by_nationality.nationality_number IS 'total_number';

ALTER TABLE migrant_by_nationality ADD CONSTRAINT migrant_by_nationality_pk PRIMARY KEY (nationality_id);

CREATE TABLE migrant_by_state (
    state_code             INTEGER NOT NULL,
    migrant_number         INTEGER,
    risk_level             CHAR(10),
    manuf_perc_in_state    NUMERIC(4,2),
    const_perc_in_state    NUMERIC(4,2),
    agric_percent_in_state NUMERIC(4,2)
);

COMMENT ON COLUMN migrant_by_state.state_code IS 'state_code';
COMMENT ON COLUMN migrant_by_state.migrant_number IS 'migrant_worker_num';
COMMENT ON COLUMN migrant_by_state.risk_level IS '''low'' , ''high''';
COMMENT ON COLUMN migrant_by_state.manuf_perc_in_state IS 'manufacturing_percentage_in_state';
COMMENT ON COLUMN migrant_by_state.const_perc_in_state IS 'construction_percentage_in_state';
COMMENT ON COLUMN migrant_by_state.agric_percent_in_state IS 'agriculture_percentage_in_state';

ALTER TABLE migrant_by_state ADD CONSTRAINT migrant_by_state_pk PRIMARY KEY (state_code);

CREATE TABLE migrant_sector_visual (
    sector_id            SMALLINT NOT NULL,
    description          VARCHAR(400),
    total_accidents_2023 INTEGER,
    accident_risk_level  CHAR(10),
    "2001_perc"          NUMERIC(5,2),
    "2005_perc"          NUMERIC(5,2),
    "2010_perc"          NUMERIC(5,2),
    "2015_perc"          NUMERIC(5,2),
    "2020_perc"          NUMERIC(5,2),
    "2023_perc"          NUMERIC(5,2)
);

COMMENT ON COLUMN migrant_sector_visual.sector_id IS 'sector';
COMMENT ON COLUMN migrant_sector_visual.description IS 'description';
COMMENT ON COLUMN migrant_sector_visual.total_accidents_2023 IS 'total_accidents_2023';
COMMENT ON COLUMN migrant_sector_visual.accident_risk_level IS 'accident_risk_level (low, medium,high)';
COMMENT ON COLUMN migrant_sector_visual."2001_perc" IS '2001_perc';
COMMENT ON COLUMN migrant_sector_visual."2005_perc" IS '2005_perc';
COMMENT ON COLUMN migrant_sector_visual."2010_perc" IS '2010_perc';
COMMENT ON COLUMN migrant_sector_visual."2015_perc" IS '2015_perc';
COMMENT ON COLUMN migrant_sector_visual."2020_perc" IS '2020_perc';
COMMENT ON COLUMN migrant_sector_visual."2023_perc" IS '2023_perc';

ALTER TABLE migrant_sector_visual ADD CONSTRAINT migrant_sector_visual_pk PRIMARY KEY (sector_id);

CREATE TABLE migrant_summary (
    total_migrant_worker INTEGER,
    year                 SMALLINT
);

COMMENT ON COLUMN migrant_summary.total_migrant_worker IS 'total_migrant_worker';
COMMENT ON COLUMN migrant_summary.year IS 'year';

CREATE TABLE nationality_sector (
    sector_id         SMALLINT NOT NULL,
    nationality_id    SMALLINT NOT NULL,
    number_of_migrant INTEGER
);

COMMENT ON COLUMN nationality_sector.sector_id IS 'sector';
COMMENT ON COLUMN nationality_sector.nationality_id IS 'nationality_id';
COMMENT ON COLUMN nationality_sector.number_of_migrant IS 'number_of_migrant';

ALTER TABLE nationality_sector ADD CONSTRAINT nationality_sector_pk PRIMARY KEY (nationality_id, sector_id);

CREATE TABLE organization (
    org_id       INTEGER NOT NULL,
    org_name     VARCHAR(250) NOT NULL,
    org_email    VARCHAR(100),
    org_descr_en VARCHAR(600),
    state_code   INTEGER NOT NULL,
    org_address  VARCHAR(350),
    org_url      VARCHAR(400),
    org_phone_no VARCHAR(25),
    org_slogan   VARCHAR(300)
);

COMMENT ON COLUMN organization.org_id IS 'org_id';
COMMENT ON COLUMN organization.org_name IS 'org_name';
COMMENT ON COLUMN organization.org_email IS 'org_email';
COMMENT ON COLUMN organization.org_descr_en IS 'org_descr_en';
COMMENT ON COLUMN organization.state_code IS 'state_code';
COMMENT ON COLUMN organization.org_address IS 'org_address';
COMMENT ON COLUMN organization.org_url IS 'org_url';
COMMENT ON COLUMN organization.org_phone_no IS 'org_phone_no';
COMMENT ON COLUMN organization.org_slogan IS 'org_slogan';

ALTER TABLE organization ADD CONSTRAINT organization_pk PRIMARY KEY (org_id);

CREATE TABLE organization_language (
    language_code CHAR(2) NOT NULL,
    org_id        INTEGER NOT NULL
);

COMMENT ON COLUMN organization_language.language_code IS 'language_code
Malay: MS
English: EN
Nepali: NE
Hindi: HI
Bengali: BN';
COMMENT ON COLUMN organization_language.org_id IS 'org_id';

CREATE UNIQUE INDEX organization_language__idxv1 ON organization_language (org_id ASC);
ALTER TABLE organization_language ADD CONSTRAINT resource_translation_pk PRIMARY KEY (language_code, org_id);

CREATE TABLE payslip (
    payslip_id                BIGINT NOT NULL,
    payslip_period_start_date DATE,
    payslip_period_end_date   DATE,
    payslip_gross_pay         NUMERIC(12,2),
    payslip_deduction         NUMERIC(12,2),
    payslip_net_pay           NUMERIC(12,2),
    wage_rate_id              INTEGER NOT NULL,
    language_code             CHAR(2) NOT NULL
);

COMMENT ON COLUMN payslip.payslip_id IS 'payslip_id';
COMMENT ON COLUMN payslip.payslip_period_start_date IS 'payslip_period_start_date';
COMMENT ON COLUMN payslip.payslip_period_end_date IS 'payslip_period_end_date';
COMMENT ON COLUMN payslip.payslip_gross_pay IS 'payslip_gross_pay';
COMMENT ON COLUMN payslip.payslip_deduction IS 'payslip_deduction';
COMMENT ON COLUMN payslip.payslip_net_pay IS 'payslip_net_pay';
COMMENT ON COLUMN payslip.wage_rate_id IS 'wage_rate_id';
COMMENT ON COLUMN payslip.language_code IS 'language_code
Malay: MS
English: EN
Nepali: NE
Hindi: HI
Bengali: BN';

CREATE UNIQUE INDEX payslip__idx ON payslip (language_code ASC);
CREATE UNIQUE INDEX payslip__idxv1 ON payslip (wage_rate_id ASC);
ALTER TABLE payslip ADD CONSTRAINT payslip_pk PRIMARY KEY (payslip_id, language_code, wage_rate_id);

CREATE TABLE payslip_item (
    payslip_item_id       INTEGER NOT NULL,
    payslip_item_type     CHAR(20),
    payslip_item_quantity NUMERIC(10,2),
    payslip_item_rate     NUMERIC(10,4),
    payslip_item_amount   NUMERIC(12,2),
    payslip_id            BIGINT NOT NULL,
    language_code         CHAR(2) NOT NULL,
    wage_rate_id          INTEGER NOT NULL
);

COMMENT ON COLUMN payslip_item.payslip_item_id IS 'payslip_item_id';
COMMENT ON COLUMN payslip_item.payslip_item_type IS 'basic, overtime, restday, holiday, allowance, bonus, deduction, other';
COMMENT ON COLUMN payslip_item.payslip_item_quantity IS 'payslip_item_quantity';
COMMENT ON COLUMN payslip_item.payslip_item_rate IS 'payslip_item_rate';
COMMENT ON COLUMN payslip_item.payslip_item_amount IS 'payslip_item_amount';
COMMENT ON COLUMN payslip_item.payslip_id IS 'payslip_id';
COMMENT ON COLUMN payslip_item.language_code IS 'language_code
Malay: MS
English: EN
Nepali: NE
Hindi: HI
Bengali: BN';
COMMENT ON COLUMN payslip_item.wage_rate_id IS 'wage_rate_id';

CREATE UNIQUE INDEX payslip_item__idx ON payslip_item (payslip_id ASC, language_code ASC, wage_rate_id ASC);
ALTER TABLE payslip_item ADD CONSTRAINT payslip_item_pk PRIMARY KEY (payslip_item_id, payslip_id, language_code, wage_rate_id);

CREATE TABLE preferred_language (
    language_code     CHAR(2) NOT NULL,
    language_eng_name CHAR(20) NOT NULL
);

COMMENT ON COLUMN preferred_language.language_code IS 'language_code
Malay: MS
English: EN
Nepali: NE
Hindi: HI
Bengali: BN';
COMMENT ON COLUMN preferred_language.language_eng_name IS 'language_eng_name';

ALTER TABLE preferred_language ADD CONSTRAINT language_pk PRIMARY KEY (language_code);

CREATE TABLE quiz_answer (
    answer_id  SERIAL PRIMARY KEY,
    is_correct CHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    result_id  BIGINT NOT NULL,
    user_id    INTEGER NOT NULL,
    topic_id   INTEGER NOT NULL,
    selected_option_id INTEGER
);

COMMENT ON COLUMN quiz_answer.answer_id IS 'answer_id';
COMMENT ON COLUMN quiz_answer.is_correct IS '''True'' ''False''';
COMMENT ON COLUMN quiz_answer.created_at IS 'created_at';
COMMENT ON COLUMN quiz_answer.result_id IS 'result_id';
COMMENT ON COLUMN quiz_answer.user_id IS 'user_id';
COMMENT ON COLUMN quiz_answer.topic_id IS 'topic_id';
COMMENT ON COLUMN quiz_answer.selected_option_id IS 'which option the user selected';

CREATE TABLE quiz_option (
    option_id                  INTEGER NOT NULL,
    option_text_en             VARCHAR(300),
    option_order               CHAR(1),
    option_explanation_text_en VARCHAR(500),
    is_correct                 CHAR(10),
    question_id                SMALLINT NOT NULL,
    answer_id                  BIGINT,
    result_id                  BIGINT,
    user_id                    INTEGER,
    topic_id                   INTEGER NOT NULL,
    legal_topic_mapping_id     INTEGER NOT NULL
);

COMMENT ON COLUMN quiz_option.option_id IS 'option_id';
COMMENT ON COLUMN quiz_option.option_text_en IS 'option_text_en';
COMMENT ON COLUMN quiz_option.option_order IS 'A,B,C,D';
COMMENT ON COLUMN quiz_option.option_explanation_text_en IS 'option_explanation_text_en';
COMMENT ON COLUMN quiz_option.is_correct IS '''True'' ''False''';
COMMENT ON COLUMN quiz_option.question_id IS 'question_id';
COMMENT ON COLUMN quiz_option.answer_id IS 'answer_id - nullable for template options';
COMMENT ON COLUMN quiz_option.result_id IS 'result_id - nullable for template options';
COMMENT ON COLUMN quiz_option.user_id IS 'user_id - nullable for template options';
COMMENT ON COLUMN quiz_option.topic_id IS 'topic_id';
COMMENT ON COLUMN quiz_option.legal_topic_mapping_id IS 'legal_topic_mapping_id';

ALTER TABLE quiz_option ADD CONSTRAINT quiz_option_pk PRIMARY KEY (option_id);

CREATE TABLE quiz_question (
    question_id            SMALLINT NOT NULL,
    question_text_en       VARCHAR(300),
    question_type          CHAR(20),
    question_order         INTEGER,
    is_active              CHAR(5) DEFAULT 'True',
    created_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    legal_topic_mapping_id INTEGER NOT NULL
);

COMMENT ON COLUMN quiz_question.question_id IS 'question_id';
COMMENT ON COLUMN quiz_question.question_text_en IS 'question_text_en';
COMMENT ON COLUMN quiz_question.question_type IS '''multiple_choice'', ''true_false''';
COMMENT ON COLUMN quiz_question.question_order IS 'question_order';
COMMENT ON COLUMN quiz_question.is_active IS '''True'', ''False''';
COMMENT ON COLUMN quiz_question.created_at IS 'created_at';
COMMENT ON COLUMN quiz_question.legal_topic_mapping_id IS 'legal_topic_mapping_id';

ALTER TABLE quiz_question ADD CONSTRAINT quiz_question_pk PRIMARY KEY (question_id, legal_topic_mapping_id);

CREATE TABLE quiz_result (
    result_id              SERIAL PRIMARY KEY,
    explanation            TEXT,
    created_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id                INTEGER NOT NULL,
    total_question         SMALLINT,
    corrected_answer_num   SMALLINT,
    score_percent          INTEGER GENERATED ALWAYS AS (
        CASE 
            WHEN total_question > 0 
            THEN ROUND(100.0 * corrected_answer_num / total_question)::INTEGER
            ELSE 0 
        END
    ) STORED,
    completion_status      CHAR(20) DEFAULT 'not_completed',
    topic_id               INTEGER NOT NULL
);

COMMENT ON COLUMN quiz_result.result_id IS 'result_id';
COMMENT ON COLUMN quiz_result.explanation IS 'Combined legal explanations for all incorrect answers in user preferred language';
COMMENT ON COLUMN quiz_result.created_at IS 'created_at';
COMMENT ON COLUMN quiz_result.user_id IS 'user_id';
COMMENT ON COLUMN quiz_result.total_question IS 'question count';
COMMENT ON COLUMN quiz_result.corrected_answer_num IS 'corrected_answer_num';
COMMENT ON COLUMN quiz_result.score_percent IS 'score_percent - automatically calculated from corrected_answer_num/total_question * 100';
COMMENT ON COLUMN quiz_result.completion_status IS '''completed'' ''not_completed"';
COMMENT ON COLUMN quiz_result.topic_id IS 'topic_id';

CREATE UNIQUE INDEX quiz_result__idx ON quiz_result (topic_id ASC);


CREATE TABLE ref_legal_section (
    legal_id               INTEGER NOT NULL,
    section_id             VARCHAR(10) NOT NULL,
    part_label             VARCHAR(20),
    title_short            VARCHAR(500),
    language_code          CHAR(2) NOT NULL,
    source_id              INTEGER NOT NULL,
    legal_title_plain      VARCHAR(200),
    legal_content_plain_en VARCHAR(1000)
);

COMMENT ON COLUMN ref_legal_section.legal_id IS 'legal_id ';
COMMENT ON COLUMN ref_legal_section.section_id IS 'section_id';
COMMENT ON COLUMN ref_legal_section.part_label IS 'part_label';
COMMENT ON COLUMN ref_legal_section.title_short IS 'title_short';
COMMENT ON COLUMN ref_legal_section.language_code IS 'language_code
Malay: MS
English: EN
Nepali: NE
Hindi: HI
Bengali: BN';
COMMENT ON COLUMN ref_legal_section.source_id IS 'source_id';
COMMENT ON COLUMN ref_legal_section.legal_title_plain IS 'legal_title_plain';
COMMENT ON COLUMN ref_legal_section.legal_content_plain_en IS 'legal_content_plain_en';

ALTER TABLE ref_legal_section ADD CONSTRAINT law_pk PRIMARY KEY (language_code, source_id, legal_id);

CREATE TABLE rights_topic (
    topic_id          INTEGER NOT NULL,
    topic_title       CHAR(50) NOT NULL,
    topic_name_en     VARCHAR(150),
    slug_text         VARCHAR(20),
    order_sequence    SMALLINT,
    is_active         CHAR(4),
    created_at        TIMESTAMP,
    topic_description VARCHAR(500)
);

COMMENT ON COLUMN rights_topic.topic_id IS 'topic_id';
COMMENT ON COLUMN rights_topic.topic_title IS 'topic_title';
COMMENT ON COLUMN rights_topic.topic_name_en IS 'category_name_en';
COMMENT ON COLUMN rights_topic.slug_text IS 'slug_text, stablekey across langugage
eg. minimum-wage, working-hours, rest-day';
COMMENT ON COLUMN rights_topic.order_sequence IS 'order_sequence';
COMMENT ON COLUMN rights_topic.is_active IS '''Yes'', ''No''';
COMMENT ON COLUMN rights_topic.created_at IS 'timestamp';
COMMENT ON COLUMN rights_topic.topic_description IS 'topic_description';

ALTER TABLE rights_topic ADD CONSTRAINT right_topic_pk PRIMARY KEY (topic_id);

CREATE TABLE source_register (
    source_id        INTEGER NOT NULL,
    source_title     VARCHAR(300),
    source_publisher VARCHAR(300),
    effective_date   DATE NOT NULL,
    source_url       VARCHAR(300),
    last_checked     DATE NOT NULL
);

COMMENT ON COLUMN source_register.source_id IS 'source_id';
COMMENT ON COLUMN source_register.source_title IS 'title';
COMMENT ON COLUMN source_register.source_publisher IS 'source_publisher';
COMMENT ON COLUMN source_register.effective_date IS 'effective_date';
COMMENT ON COLUMN source_register.source_url IS 'source_url';
COMMENT ON COLUMN source_register.last_checked IS 'last_checked';

ALTER TABLE source_register ADD CONSTRAINT source_register_pk PRIMARY KEY (source_id);

CREATE TABLE story_media (
    story_media_id INTEGER NOT NULL,
    story_id       INTEGER NOT NULL,
    media_id       BIGINT NOT NULL,
    language_code  CHAR(2) NOT NULL
);

COMMENT ON COLUMN story_media.story_media_id IS 'story_media_id';
COMMENT ON COLUMN story_media.story_id IS 'story_id';
COMMENT ON COLUMN story_media.media_id IS 'media_id';
COMMENT ON COLUMN story_media.language_code IS 'language_code
Malay: MS
English: EN
Nepali: NE
Hindi: HI
Bengali: BN';

ALTER TABLE story_media ADD CONSTRAINT story_media_pk PRIMARY KEY (story_media_id, story_id, language_code);

CREATE TABLE survivor_story (
    story_id       INTEGER NOT NULL,
    story_title_en VARCHAR(100),
    story_body_en  CHAR(300),
    language_code  CHAR(2) NOT NULL
);

COMMENT ON COLUMN survivor_story.story_id IS 'story_id';
COMMENT ON COLUMN survivor_story.story_title_en IS 'story_title_en';
COMMENT ON COLUMN survivor_story.story_body_en IS 'story_body_en';
COMMENT ON COLUMN survivor_story.language_code IS 'language_code
Malay: MS
English: EN
Nepali: NE
Hindi: HI
Bengali: BN';

CREATE UNIQUE INDEX survivor_story__idx ON survivor_story (language_code ASC);
ALTER TABLE survivor_story ADD CONSTRAINT survivor_story_pk PRIMARY KEY (story_id, language_code);

CREATE TABLE "user" (
    user_id       SERIAL PRIMARY KEY,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    language_code CHAR(2)
);

COMMENT ON COLUMN "user".user_id IS 'user_id - auto-generated';
COMMENT ON COLUMN "user".created_at IS 'created_at - automatically set to current timestamp';
COMMENT ON COLUMN "user".language_code IS 'language_code
Malay: MS
English: EN
Nepali: NE
Hindi: HI
Bengali: BN';



CREATE TABLE work_log (
    work_log_id         BIGINT NOT NULL,
    work_date           DATE,
    work_hours_regular  NUMERIC(5,2),
    work_hours_overtime NUMERIC(5,2),
    work_hours_restday  NUMERIC(5,2),
    work_hours_holiday  NUMERIC(5,2),
    work_notes          VARCHAR(10000),
    employ_id           BIGINT NOT NULL,
    user_id             INTEGER NOT NULL
);

COMMENT ON COLUMN work_log.work_log_id IS 'work_log_id';
COMMENT ON COLUMN work_log.work_date IS 'work_date';
COMMENT ON COLUMN work_log.work_hours_regular IS 'work_hours_regular';
COMMENT ON COLUMN work_log.work_hours_overtime IS 'work_hours_overtime';
COMMENT ON COLUMN work_log.work_hours_restday IS 'work_hours_restday';
COMMENT ON COLUMN work_log.work_hours_holiday IS 'work_hours_holiday';
COMMENT ON COLUMN work_log.work_notes IS 'work_notes';
COMMENT ON COLUMN work_log.employ_id IS 'employ_id';
COMMENT ON COLUMN work_log.user_id IS 'user_id';

CREATE UNIQUE INDEX work_log__idx ON work_log (employ_id ASC, user_id ASC);
ALTER TABLE work_log ADD CONSTRAINT work_log_pk PRIMARY KEY (work_log_id, employ_id, user_id);

-- Add foreign key constraints
ALTER TABLE quiz_answer ADD CONSTRAINT answer_result_fk FOREIGN KEY (result_id) REFERENCES quiz_result (result_id);
ALTER TABLE quiz_answer ADD CONSTRAINT answer_selected_option_fk FOREIGN KEY (selected_option_id) REFERENCES quiz_option (option_id);
ALTER TABLE quiz_option ADD CONSTRAINT option_question_fk FOREIGN KEY (question_id, legal_topic_mapping_id) REFERENCES quiz_question (question_id, legal_topic_mapping_id);
ALTER TABLE quiz_option ADD CONSTRAINT option_topic_fk FOREIGN KEY (topic_id) REFERENCES rights_topic (topic_id);
ALTER TABLE contract_clause_match ADD CONSTRAINT clause_contract_match_fk FOREIGN KEY (clause_id) REFERENCES clause (clause_id);
ALTER TABLE contract_issue ADD CONSTRAINT contract_contract_issue FOREIGN KEY (contract_id, user_id) REFERENCES contract (contract_id, user_id);
ALTER TABLE contract_text ADD CONSTRAINT contract_contract_text_fk FOREIGN KEY (contract_id, user_id) REFERENCES contract (contract_id, user_id);
ALTER TABLE contract_issue ADD CONSTRAINT contract_issue_clause FOREIGN KEY (clause_id) REFERENCES clause (clause_id);
ALTER TABLE contract ADD CONSTRAINT contract_media FOREIGN KEY (media_id) REFERENCES media_asset (media_id);
ALTER TABLE contract_summary ADD CONSTRAINT contract_summary_fk FOREIGN KEY (contract_id, user_id) REFERENCES contract (contract_id, user_id);
ALTER TABLE contract_clause_match ADD CONSTRAINT contract_text_match_fk FOREIGN KEY (contract_text_id, contract_id, user_id) REFERENCES contract_text (contract_text_id, contract_id, user_id);
ALTER TABLE contract_translation ADD CONSTRAINT contract_text_transl_fk FOREIGN KEY (contract_text_id, contract_id, user_id) REFERENCES contract_text (contract_text_id, contract_id, user_id);
ALTER TABLE work_log ADD CONSTRAINT employ_work_log_fk FOREIGN KEY (employ_id, user_id) REFERENCES employment_detail (employ_id, user_id);
ALTER TABLE ref_legal_section ADD CONSTRAINT language_leg_fk FOREIGN KEY (language_code) REFERENCES preferred_language (language_code);
ALTER TABLE payslip ADD CONSTRAINT language_payslip FOREIGN KEY (language_code) REFERENCES preferred_language (language_code);
ALTER TABLE organization_language ADD CONSTRAINT language_resource_trans_fk FOREIGN KEY (language_code) REFERENCES preferred_language (language_code);
ALTER TABLE survivor_story ADD CONSTRAINT language_story_fk FOREIGN KEY (language_code) REFERENCES preferred_language (language_code);
ALTER TABLE legal_topic_mapping ADD CONSTRAINT law_legal_topic FOREIGN KEY (language_code, source_id, legal_id) REFERENCES ref_legal_section (language_code, source_id, legal_id);
ALTER TABLE quiz_question ADD CONSTRAINT leg_topic_ques_fk FOREIGN KEY (legal_topic_mapping_id) REFERENCES legal_topic_mapping (legal_topic_mapping_id);
ALTER TABLE clause ADD CONSTRAINT legal_clause_fk FOREIGN KEY (language_code, source_id, legal_id) REFERENCES ref_legal_section (language_code, source_id, legal_id);
ALTER TABLE derived_wage_rate ADD CONSTRAINT legal_derived_wage_fk FOREIGN KEY (language_code, source_id, legal_id) REFERENCES ref_legal_section (language_code, source_id, legal_id);
ALTER TABLE story_media ADD CONSTRAINT media_asset_story_media_fk FOREIGN KEY (media_id) REFERENCES media_asset (media_id);
ALTER TABLE migrant_by_nationality ADD CONSTRAINT nationality_migrnt_num_fk FOREIGN KEY (nationality_id) REFERENCES dim_nationality (nationality_id);
ALTER TABLE nationality_sector ADD CONSTRAINT nationality_sector_dim_fk FOREIGN KEY (sector_id) REFERENCES dim_sector (sector_id);
ALTER TABLE nationality_sector ADD CONSTRAINT nationality_sector_fk FOREIGN KEY (nationality_id) REFERENCES migrant_by_nationality (nationality_id);
ALTER TABLE organization ADD CONSTRAINT org_state_fk FOREIGN KEY (state_code) REFERENCES dim_state (state_code);
ALTER TABLE organization_language ADD CONSTRAINT org_transl_lang_fk FOREIGN KEY (org_id) REFERENCES organization (org_id);
ALTER TABLE payslip_item ADD CONSTRAINT pay_slip_item FOREIGN KEY (payslip_id, language_code, wage_rate_id) REFERENCES payslip (payslip_id, language_code, wage_rate_id);
ALTER TABLE quiz_option ADD CONSTRAINT question_option_fk FOREIGN KEY (question_id, legal_topic_mapping_id) REFERENCES quiz_question (question_id, legal_topic_mapping_id);
ALTER TABLE dim_sector ADD CONSTRAINT relation_42 FOREIGN KEY (sector_id) REFERENCES migrant_sector_visual (sector_id);
ALTER TABLE quiz_result ADD CONSTRAINT relation_66 FOREIGN KEY (user_id) REFERENCES "user" (user_id);
ALTER TABLE ref_legal_section ADD CONSTRAINT source_legal_fk FOREIGN KEY (source_id) REFERENCES source_register (source_id);
ALTER TABLE migrant_by_state ADD CONSTRAINT state_migrant_fk FOREIGN KEY (state_code) REFERENCES dim_state (state_code);
ALTER TABLE story_media ADD CONSTRAINT story_story_media FOREIGN KEY (story_id, language_code) REFERENCES survivor_story (story_id, language_code);
ALTER TABLE quiz_result ADD CONSTRAINT topic_explanation_fk FOREIGN KEY (topic_id) REFERENCES rights_topic (topic_id);
ALTER TABLE legal_topic_mapping ADD CONSTRAINT topic_legal_topic_fk FOREIGN KEY (topic_id) REFERENCES rights_topic (topic_id);
ALTER TABLE contract ADD CONSTRAINT user_contract FOREIGN KEY (user_id) REFERENCES "user" (user_id);
ALTER TABLE employment_detail ADD CONSTRAINT user_employ_fk FOREIGN KEY (user_id) REFERENCES "user" (user_id);
ALTER TABLE "user" ADD CONSTRAINT user_language_fk FOREIGN KEY (language_code) REFERENCES preferred_language (language_code);
ALTER TABLE payslip ADD CONSTRAINT wage_payslip_fk FOREIGN KEY (wage_rate_id) REFERENCES derived_wage_rate (wage_rate_id);

-- =============================================================================
-- AUTO-CALCULATION FUNCTIONS FOR QUIZ_RESULT
-- =============================================================================

-- Function to auto-calculate total_question and explanation when quiz is completed
CREATE OR REPLACE FUNCTION update_quiz_result_auto_fields()
RETURNS TRIGGER AS $$
BEGIN
    -- Only calculate when completion_status changes to 'completed'
    IF NEW.completion_status = 'completed' AND OLD.completion_status != 'completed' THEN
        
        -- Auto-calculate total_question
        NEW.total_question := (
            SELECT COUNT(DISTINCT qa.selected_option_id)
            FROM quiz_answer qa 
            WHERE qa.result_id = NEW.result_id 
            AND qa.user_id = NEW.user_id
        );
        
        -- Auto-calculate corrected_answer_num
        NEW.corrected_answer_num := (
            SELECT COUNT(*)
            FROM quiz_answer qa 
            WHERE qa.result_id = NEW.result_id 
            AND qa.user_id = NEW.user_id 
            AND qa.is_correct = 'True'
        );
        
        -- Auto-generate explanation for wrong answers
        NEW.explanation := (
            SELECT COALESCE(
                STRING_AGG(DISTINCT rls.legal_content_plain_en, E'\n\n---\n\n'), 
                'All answers correct! No legal violations found.'
            )
            FROM quiz_answer qa
            JOIN quiz_option qo ON qa.selected_option_id = qo.option_id
            JOIN quiz_question qq ON qo.question_id = qq.question_id
            JOIN legal_topic_mapping ltm ON qq.legal_topic_mapping_id = ltm.legal_topic_mapping_id
            JOIN ref_legal_section rls ON ltm.legal_id = rls.legal_id 
                AND ltm.language_code = rls.language_code 
                AND ltm.source_id = rls.source_id
            JOIN "user" u ON qa.user_id = u.user_id
            WHERE qa.result_id = NEW.result_id 
            AND qa.user_id = NEW.user_id
            AND qa.is_correct = 'False'
            AND rls.language_code = COALESCE(u.language_code, 'EN')
        );
        
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to auto-calculate fields when quiz is completed
CREATE TRIGGER quiz_result_auto_calculate
    BEFORE UPDATE ON quiz_result
    FOR EACH ROW
    EXECUTE FUNCTION update_quiz_result_auto_fields();

-- =============================================================================
-- HELPER FUNCTION FOR MANUAL CALCULATION (if needed)
-- =============================================================================

-- Function to manually recalculate quiz result fields
CREATE OR REPLACE FUNCTION recalculate_quiz_result(
    p_result_id BIGINT,
    p_user_id INTEGER
) RETURNS VOID AS $$
BEGIN
    UPDATE quiz_result 
    SET 
        total_question = (
            SELECT COUNT(DISTINCT qa.selected_option_id)
            FROM quiz_answer qa 
            WHERE qa.result_id = p_result_id 
            AND qa.user_id = p_user_id
        ),
        corrected_answer_num = (
            SELECT COUNT(*)
            FROM quiz_answer qa 
            WHERE qa.result_id = p_result_id 
            AND qa.user_id = p_user_id 
            AND qa.is_correct = 'True'
        ),
        explanation = (
            SELECT COALESCE(
                STRING_AGG(DISTINCT rls.legal_content_plain_en, E'\n\n---\n\n'), 
                'All answers correct! No legal violations found.'
            )
            FROM quiz_answer qa
            JOIN quiz_option qo ON qa.selected_option_id = qo.option_id
            JOIN quiz_question qq ON qo.question_id = qq.question_id
            JOIN legal_topic_mapping ltm ON qq.legal_topic_mapping_id = ltm.legal_topic_mapping_id
            JOIN ref_legal_section rls ON ltm.legal_id = rls.legal_id 
                AND ltm.language_code = rls.language_code 
                AND ltm.source_id = rls.source_id
            JOIN "user" u ON qa.user_id = u.user_id
            WHERE qa.result_id = p_result_id 
            AND qa.user_id = p_user_id
            AND qa.is_correct = 'False'
            AND rls.language_code = COALESCE(u.language_code, 'EN')
        )
    WHERE result_id = p_result_id AND user_id = p_user_id;


END;
$$ LANGUAGE plpgsql;

DROP TABLE IF EXISTS contract_clause_match CASCADE;
DROP TABLE IF EXISTS contract_issue CASCADE;
DROP TABLE IF EXISTS contract_summary CASCADE;
DROP TABLE IF EXISTS contract_text CASCADE;
DROP TABLE IF EXISTS contract_translation CASCADE;
DROP TABLE IF EXISTS payslip_item CASCADE;
DROP TABLE IF EXISTS payslip CASCADE;
DROP TABLE IF EXISTS derived_wage_rate CASCADE;
DROP TABLE IF EXISTS employment_detail CASCADE;
DROP TABLE IF EXISTS contract CASCADE;
DROP TABLE IF EXISTS clause CASCADE;